language: cpp

matrix:
    include:
        - os: linux
          addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-8
                    - cmake
          env:
            - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

script:
    - mkdir build && cd build/
    - cmake .. && make